name: 新功能请求
description: 你有新的功能请求？在这里填写下吧
labels: ['enhancement']
title: "[Feature] "
assignees: ADJazzzz

body:
    - type: textarea
      id: describe
      validations:
          required: true
      attributes:
          label: '功能描述'
          description: |
              描述你想要的功能
